/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.relay42.iot.sensor.data.avro;
@org.apache.avro.specific.AvroGenerated
public enum IoTSensorEventTypeKafka implements org.apache.avro.generic.GenericEnumSymbol<IoTSensorEventTypeKafka> {
  SENSOR_READINGS  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"IoTSensorEventTypeKafka\",\"namespace\":\"com.relay42.iot.sensor.data.avro\",\"symbols\":[\"SENSOR_READINGS\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
