/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.relay42.iot.sensor.data.avro;
@org.apache.avro.specific.AvroGenerated
public enum SensorType implements org.apache.avro.generic.GenericEnumSymbol<SensorType> {
  THERMOSTAT, HEART_RATE, CAR_FUEL_LEVEL  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"SensorType\",\"namespace\":\"com.relay42.iot.sensor.data.avro\",\"symbols\":[\"THERMOSTAT\",\"HEART_RATE\",\"CAR_FUEL_LEVEL\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
